import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run media`; not hand-authored source.
    "public/**",
  ]),
  {
    rules: {
      /**
       * A bare `return` on its own line gets a semicolon inserted, silently
       * returning undefined. That exact mistake blanked the Sanity Studio: the
       * structure resolver returned nothing, and neither tsc nor the build
       * complained, because a module that returns undefined is still valid.
       *
       * no-unreachable catches it — the expression after the return becomes
       * dead code. It is an error, not a warning, because the failure it
       * prevents is invisible until someone opens the page.
       */
      "no-unreachable": "error",
    },
  },
]);

export default eslintConfig;
